### ISSUE TITLE
cannot use import statement outside a module

### ISSUE THREAD

**Issue by JCWardle** [samuelgozi/firebase-auth-lite#17]
I'm getting this error in NextJS with Node version 14. The fix I'd suggest is to change the import to a require for better support across older versions of node.

```
import humanReadableErrors from './errors.json';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.firebase-auth-lite (/app/.next/server/static/development/pages/_app.js:2896:18)
    at __webpack_require__ (/app/.next/server/static/development/pages/_app.js:23:31)
    at Module../src/singletons/authentication.js (/app/.next/server/static/development/pages/_app.js:2459:76)
    at __webpack_require__ (/app/.next/server/static/development/pages/_app.js:23:31)
    at Object../src/singletons/index.js (/app/.next/server/static/development/pages/_app.js:2600:46)
    at __webpack_require__ (/app/.next/server/static/development/pages/_app.js:23:31)
    at Module../pages/_app.js (/app/.next/server/static/development/pages/_app.js:1888:74)
    at __webpack_require__ (/app/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/app/.next/server/static/development/pages/_app.js:2697:18)
    at __webpack_require__ (/app/.next/server/static/development/pages/_app.js:23:31)
```

**Comment by samuelgozi** [comment]
Thanks for opening an issue.
In order to keep code small and simple, this lib doesn't transpile(compile) to a specific target.
You'll need to transpile it yourself to the target you intend on using.
I think this can help:
https://github.com/martpie/next-transpile-modules

If not let me know. But unfortunately, I won't regress the code for legacy support.

**Comment by deepfriedbrain** [comment]
@samuelgozi 

I had a similar issue and it's based on Jekyll. Do you know how I get it transpiled? I tried it with babel.io but keep getting "exports is not defined error". Do you have any suggestions for me?

**Comment by samuelgozi** [comment]
@deepfriedbrain I never used Jekyll, but I'll try to help.
Are you using webpack with Jekyll to bundle your code?

**Comment by deepfriedbrain** [comment]
@samuelgozi I use jekyll-assets plugin to bundle the js and css. In the long term, I could look at adding webpack and babel, but I want to do a quick test of this library and compare the performance with what I'm getting with Firebase Auth. Using Firebase Auth is almost a no-go for me at this point.

**Comment by samuelgozi** [comment]
@deepfriedbrain You will need to use a bundler that lets you transpile dependencies.
A good one is webpack, but if you want a simpler one I recommend using Parcel.

Unfortunately im not familiar with the Jekyll or its ecosystem, so I can't point out any specific tool. But from what I could see, the recommended way is to use webpack.

**Comment by deepfriedbrain** [comment]
@samuelgozi Sure I'll look into it. I was hoping for a quick way to transpile it into an ES5 JS. I have been using Webpack on my other projects and familiar with it, but I've not used it with Jekyll before. Since I'm already using (ruby gem) jekyll-assets plugin, which has been doing a fine job with bundling, I don't know how adding Webpack would play out.

But thanks for your help.
